= Probleme
Probleme kann es bei jeder Präsentation geben. Hier sind einige Möglichkeiten damit umzugehen.

== Zeitprobleme
Sollten von einer 30 Minuten Präsentation - weswegen auch immer - nur 20 Minuten bleiben, habt ihr euch am besten VOR der Präsentation Gedanken darüber gemacht welche Teile kürzer gehalten oder gar ganz wegfallen können.

IMPORTANT: Haltet euch an die vorgegebenen Zeitrahmen!

== Technische Probleme
Sollte es Probleme mit eurem Computer etc. geben versucht möglichst die Präsentation währenddessen voranzutreiben. Redet, seid engagiert! Es ist nicht zu dramatisch, wenn mal eine Folie oder eine Grafik fehlt, solange ihr das erklären / zeichnen / beschreiben etc. könnt. Das lässt euch eher professionell erscheinen, als wenn ihr auf euren Computer einschlagt ;-)

== Menschliche Probleme
Und noch einmal: Üben, üben, üben! Nur das hilft wirklich. Wenn euch aber doch einmal ein kleiner Fehler unterläuft versucht nicht gleich euch bis in alle Ewigkeit zu entschuldigen. Das bringt euch nur aus dem Konzept und hilft niemandem. Sprecht ihr den Fehler nicht an und macht weiter wie bisher, kann es sogar passieren, dass den Fehler einfach niemand bemerkt -> Problem gelöst.

== Publikum
Was, wenn jemand eure Präsentation unterbricht und euch / eure Daten und Theorien komplett ignoriert oder für Blödsinn hält?

. Ruhig bleiben. Panik bringt jetzt nichts.
. Sinnvolle Gegenfragen formulieren / Fragen konkretisieren lassen.
. Genau zuhören WARUM man unterbrochen wurde. Evtl. kann man freundlich darauf hinweisen, dass diese Frage später noch geklärt wird.
. Wenn man weiß, dass der Unterbrecher recht hat (“Euer Produkt ist mies, wir können es nicht leiden, es bringt uns nicht weiter!”), gebt es einfach zu. Es gibt nicht schlimmeres als während einer Präsentation zu lügen, wenn das Gegenüber genau weiß, dass man lügt!

Generell solltet ihr euch um die Wahrheit und Kooperation bemühen. Dazu gehört, dass ihr als Team (“WIR haben das verbockt!”) zusammensteht und Lösungen anbietet. Wenn das Publikum erst einmal der Meinung ist, dass IHR (als Team) das Problem seid, sieht es übel aus.



