= Einleitung (oder: Warum das Ganze?)

Reden/Präsentationen halten sollte uns eigentlich aus historischen Gründen leicht fallen - tut es aber meistens nicht. Das ist an sich auch gar nicht schlimm, denn man kann viel dafür tun, dass eine Präsentation trotzdem gelingt. Dazu versuche ich einige Tipps und Tricks zusammen zu tragen und euch an die Hand zu geben, damit eure Präsentation möglichst gut wird und im Gedächtnis bleibt.
Dazu noch eins vorweg: Es kommt nicht darauf an WER ihr seid, sondern ganz einfach darauf, möglichst charismatisch und stark aufzutreten, auch wenn das schwer fällt. Einige der größten und am häufigsten zitierten Ansprachen aus der Vergangenheit sind von Abraham Lincoln (Gettysburg) und Winston Churchill (“We shall fight...”), beide zum damaligen Zeitpunkt wenig beliebte noch bekannte Menschen. Das Einzige worauf es ihnen ankam war ihre Zuhörer zu respektieren (sie nicht für dumm zu verkaufen) und die ungeschönte Wahrheit zu sagen, ihre “Geschichte” gut zu verkaufen.
Dazu aber später mehr. Fangen wir an.



